import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={`${inter.className} bg-gradient-to-br from-[#4dc9e6] to-[#210cae] bg-no-repeat bg-cover`}>
        {children}
      </body>
    </html>
  );
}
